version: '3.8'

services:
  gopherdb:
    container_name: gopherdb
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - ../../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gophernetwork

networks:
  gophernetwork:
